# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-10 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaNatural',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('apellido', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'default_permissions': (),
                'verbose_name': 'PersonaNatural',
                'verbose_name_plural': 'PersonaNatural',
                'permissions': (('add_personanatural', 'Puede agregar PersonaNatural'), ('change_personanatural', 'Puede actualizar PersonaNatural'), ('delete_personanatural', 'Puede eliminar PersonaNatural'), ('list_personanatural', 'Puede listar PersonaNatural'), ('get_personanatural', 'Puede obtener PersonaNatural'), ('listform_personanatural', 'Puede listar PersonaNatural en Formularios')),
                'db_table': 'persona_persona_natural',
            },
        ),
    ]
