# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-10 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHobby',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('estado', models.CharField(default='1', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'TipoHobby',
                'db_table': 'persona_hobby',
                'default_permissions': (),
                'permissions': (('add_hobby', 'Puede agregar TipoHobby'), ('change_hobby', 'Puede actualizar TipoHobby'), ('delete_hobby', 'Puede eliminar TipoHobby'), ('list_hobby', 'Puede listar TipoHobby'), ('get_hobby', 'Puede obtener TipoHobby'), ('listform_hobby', 'Puede listar TipoHobby en Formularios')),
                'verbose_name': 'TipoHobby',
            },
        ),
    ]
