# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-10 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_tipohobby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('tipo_hobby', models.ForeignKey(db_column='tipo_hobby_id', on_delete=django.db.models.deletion.PROTECT, related_name='hobby_tipo_hobby_set', to='persona.TipoHobby')),
            ],
            options={
                'verbose_name': 'Hobby',
                'db_table': 'persona_hobbys',
                'verbose_name_plural': 'Hobby',
                'permissions': (('add_hobby', 'Puede agregar Hobby'), ('change_hobby', 'Puede actualizar Hobby'), ('delete_hobby', 'Puede eliminar Hobby'), ('list_hobby', 'Puede listar Hobby'), ('get_hobby', 'Puede obtener Hobby'), ('listform_hobby', 'Puede listar Hobby en Formularios')),
                'default_permissions': (),
            },
        ),
    ]
