# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-10 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_hobby'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipohobby',
            table='persona_tipo_hobby',
        ),
    ]
