# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-10 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_auto_20170410_1616'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hobby',
            table='persona_hobby',
        ),
    ]
