# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-10 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_auto_20170410_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='tipo_hobby',
        ),
    ]
